CC = gcc

all: psc filter encoder

psc: psc.c
	$(CC) psc.c -o psc

filter: filter_c/filter.c
	$(CC) -m32 -g -fno-stack-protector -z execstack filter_c/filter.c -o filter

encoder: encoder_c/encoder.c
	$(CC) encoder_c/encoder.c -o encoder

.Phony: clean
clean:
	rm -rf psc filter encoder
	rm -rf run.c run # generated by psc
