.TH psc 7 "Last update: August 07, 2020"

.SH NAME
psc \- printable shellcode compiler

.SH SYNOPSIS
.B psc
.B [btechn]
"shellcode"

.SH DESCRIPTION
Converts arbitrary x86 shellcode into printable shellcode.

Whenever a C stub is generated, psc will encode the string as a binary byte
.B (-b)
sequence.
This prevents the C compiler from interpreting any incidental escape sequences that
are part of the printable shellcode.

For examples, refer end of this manual.

.SH OPTIONS
.TP
.BR -b
output in
.I binary string format
for C

.TP
.BR -t
printable shellcode with
.I testing shim

.TP
.BR -e
only
.I encoded payload
of the printable shellcode 

.TP
.BR -c
.I c program
to try out the (printable) shellcode

.TP
.BR -n
skip printing
.I newline
after printable shellcode

.TP
.BR -h
show help

.SH EXAMPLES
.TP
\fBpsc "\\xcd\\x80.."
Prints out the printable shellcode.

.TP
\fBpsc -b "\\xcd\\x80.."
Prints out the printable shellcode in format to embed in C code.

.TP
\fBpsc -c "\\xcd\\x80.." >run.c
Generates a C stub to run the printable shellcode.
For compilation instructions, refer to comments inside run.c.

.ti -7
\l' 5i.'

.TP
\fBpsc -e "\\xcd\\x80.."
Prints only the encoded payload of the printable shellcode.

.TP
\fBpsc -eb "\\xcd\\x80.."
Prints only the encoded payload of the printable shellcode in format to embed in C code.

.ti -7
\l' 5i.'

.TP
\fBpsc -t "\\xcd\\x80.."
Prints printable shellcode with the testing shim.
Note that the shellcode is no longer printable due to the testing shim.

.TP
\fBpsc -tb "\\xcd\\x80.."
Prints printable shellcode with the testing shim in format to embed in C code.
Note that the shellcode is no longer printable due to the testing shim.

.TP
\fBpsc -tc "\\xcd\\x80.." >run.c
Generates C stub with the \fItesting shim\fR embedded in the printable shellcode.
Note that the shellcode is no longer printable due to the testing shim.
For compilation instructions, refer to comments inside run.c.

.fi

.SH AUTHORS
Dhrumil Patel <201601228@daiict.ac.in>,
Aditya Basu <aditya.basu@psu.edu>
